### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by stefuNz** [hubot-scripts/hubot-bitbucket-pr#4]
Hey,

i'm using Hubot for rocket chat and i'm guessing what the hubot base url could be.

Also, if self hosted bitbucket server, which hook addon should i use with which options?

**Comment by tshedor** [comment]
@stefuNz 

The Hubot base URL is your public-facing hubot address, such as hubot.herokuapp.com. This is an accessible endpoint for Bitbucket POSTs.

On a self-hosted Bitbucket server, I'm honestly unsure. I don't have any experience with self-hosted Bitbucket and don't know the interface. If you're using the new Bitbucket and version `v0.4 <=` of this plugin, you'll want to create a Webhook [using this interface](https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html#ManageWebhooks-create_webhookCreatingWebhooks).

**Comment by tshedor** [comment]
Hi @stefuNz, I'm marking this issue as closed. If you have any other questions, please let me know.
