### ISSUE TITLE
How to install from this repo?

### ISSUE THREAD

**Issue by otherdave** [hubot-scripts/hubot-bitbucket-pr#6]
Hey all,

Not sure of the best place to ask this question.

When I run `npm install hubot-bitbucket-pr --save` as suggested in the README I seem to get version 0.2.0 and I'm not sure where it's pulling from. To get a newer version I have to download the script and manually put it in my `/scripts` folder. I see that there's a version 0.3.0 and 0.4.0 in this repo. What's the recommended way to upgrade?

I'm new to Hubot so I apologize if this is a total newbie question.

**Comment by tshedor** [comment]
Hey @otherdave. You're in good newbie company. This is my first NPM module, and while I incremented the version number, tagged, added a release on GitHub, etc. I never triggered `npm publish`. 

Thanks for catching this. I've [updated the module on npm](https://www.npmjs.com/package/hubot-bitbucket-pr) - sorry for the confusion. Running `npm update hubot-bitbucket-pr --save` should get you to version `0.5.0`.

Please let me know if that doesn't work for you.

**Comment by otherdave** [comment]
@tshedor thanks for the quick up. I'm upgraded & working!

**Comment by tshedor** [comment]
Excellent news
